### ISSUE TITLE
Fails to compile in MSVC

### ISSUE THREAD

**Issue by thecppzoo** [atomgalaxy/libciabatta#7]
https://godbolt.org/z/EEzeTh

Unfortunately the code does not work with MSVC compilers.  Any ideas for a workaround?

It seems the problem is the initialization, there seems to be a bug in which the base class `mixin` is not allowed for initialization in the constructor:
https://godbolt.org/z/mq2TAc

**Comment by thecppzoo** [comment]
Created a report with the MSVC people
https://developercommunity.visualstudio.com/content/problem/1110083/msvc-compiler-versions-fail-to-compile-valid-code.html

**Comment by atomgalaxy** [comment]
Thanks! I'm setting up a vc++ capable environment RN so I'll triage this weekend if I can.

**Comment by atomgalaxy** [comment]
Fixed.
